### PR TITLE
Feat/add expected tag values

### PR DESCRIPTION
**Pull request by rinzool**
### Related Issue
https://github.com/turbot/steampipe-mod-aws-tags/issues/26

### How
* Create a new file `controls/expected_tag_values.sp` similar to `mandatory.sp`
*  For each tag in variable `expected_tag_values`, we check, for all resources possessing the tag, if the value is one of the listed value

### Result

image

````console
$ steampipe check benchmark.expected_tag_values --var='expected_tag_values={"Environment": ["Production", "Staging"]}'

Expected Tag Values ...................................................................................................................................................... 5 / 6 [==========]
| 
+ Access Analyzer analyzers should have appropriate tag values ........................................................................................................... 0 / 0 [          ]
| 
+ API Gateway stages should have appropriate tag values .................................................................................................................. 0 / 0 [          ]
| 
+ CloudFront distributions should have appropriate tag values ............................................................................................................ 0 / 0 [          ]
| 
+ CloudTrail trails should have appropriate tag values ................................................................................................................... 0 / 0 [          ]
| 
+ CloudWatch alarms should have appropriate tag values ................................................................................................................... 0 / 0 [          ]
| 
+ CloudWatch log groups should have appropriate tag values ............................................................................................................... 1 / 2 [====      ]
| | 
| ALARM: /aws/test-log-group2 has a wrong value for tag Environment. "prod" must be one of ["Production", "Staging"]. ................................................ 
| OK   : /aws/test-log-group1 has a good value for tag Environment. .................................................................................................. 
```

### CODE REVIEW

**Comment by dim-ops** [comment]
Great feature, I need of it ! @misraved

**Comment by rinzool** [comment]
Hi @e-gineer, I just pushed a [commit](https://github.com/turbot/steampipe-mod-aws-tags/pull/27/commits/0de23f7ec01722d14b2aa9ffcab1991ab1352dfa) to add the use of `LIKE` operator
It works as expected, but it may increase a lot the duration of queries if there are a lot of wildcards used (without any wildcards it's very fast :+1:)
I used the `json_array_elements_text` function to explode expected values so they can be compared to real tag value using `LIKE`, and then I group by resources and aggregated the tag comparison using `bool_or` operator. I did not find any other (and faster) solution, but if anyone has a better idea, please tell me! :pray: :grinning:

**Comment by rinzool** [comment]
Hi @e-gineer @misraved, did you find some time to look at this PR / Issue? :pray:

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@rinzool I've added some suggestions, can you please have a look when you get a chance? Thanks!

**Comment by rinzool** [comment]
Thanks @cbruno10! You were write we needed a double backslash to escape wildcard `\\_`
And thanks for the suggestion of better descriptions and naming :+1:

**Comment by rinzool** [comment]
Hi @cbruno10, I like your ideas! 
I just committed them, can you please see it it works fine for you? :pray: 

I added the display of possible values, but you are right it makes a very long line.. :confused: Can you try it and tell me what you think please?

**Comment by cbruno10** [comment]
@rinzool Thanks for making the changes, I ran the controls again for various scenarios and agree that sometimes the reasons are long, especially when the keys/values are long.

Based on your changes, here are my suggestions for new reasons:
- OK state:
  - When all tags for a resource have expected tag values or do not have the expected tag keys: `i-123 has expected tag values.`
  - When resource has no tags: `i-123 has no tags.`
  - When no expected tag values are set: `i-123 has tags but no expected tag values are set.`
- Alarm state:
  - When one or more tag for a resource has an unexpected tag value: `i-123 has unexpected tag values for tags: Name, Environment.`

In general, these are simpler than the current reasons, but I found the current ones to be a bit long (even the one in OK state), e.g.,
```
+ EC2 instances should have appropriate tag values ................................................................................................ 3 / 4 [==========]
  |
  ALARM: App Dev has unexpected tag values for tag keys: Environment,Name. Expected values: ["Prod", "Staging", "Dev"],["Demo"]. .............. us-east-1 123456789012
  ALARM: App Staging has unexpected tag values for tag keys: Environment,Name. Expected values: ["Prod", "Staging", "Dev"],["Demo"]. .......... us-east-1 123456789012
  ALARM: Demo has unexpected tag values for tag keys: Environment. Expected values: ["Prod", "Staging", "Dev"]. ............................... us-east-1 123456789012
  OK   : i-0bd0fba70e1c158c9 has expected tag values or no tag values for tag keys: Environment,Name,StrictCostCenter,created_by. ............. us-east-1 123456789012
```

If a user needs more info, in particular in the alarm case, then they can manually compare the resources' tags and the expected tag values.

Thoughts?

**Comment by rinzool** [comment]
And voilà @cbruno10 :tada: 
I updated the messages with your ideas, I think it's quite explicit but not too long now :ok_hand:

**Review by cbruno10 — APPROVED** [review]

**Comment by cbruno10** [comment]
@rinzool The new reasons look great, thanks again for your work on this PR!

**Pull request merged**
